[build]
  command = "npm run build"
  publish = "dist"

[dev]
  command = "vite"
  port = 8080
  targetPort = 3000
  publish = "dist"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
